version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user/SchoolSystem
hooks:
  ApplicationStart:
    - location: /home/ec2-user/SchoolSystem/scripts/application_start.sh
      timeout: 3000
